# Generated by Django 3.1.4 on 2020-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('user', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('fails', models.PositiveSmallIntegerField(default=0)),
                ('login_link', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('reset_link', models.CharField(blank=True, max_length=225, null=True, unique=True)),
                ('Question_one', models.CharField(max_length=50)),
                ('EmojiStr_one', models.TextField(max_length=100)),
                ('EmojiArray_one', models.CharField(max_length=20)),
                ('PIN_one', models.CharField(max_length=4)),
                ('Question_two', models.CharField(max_length=50)),
                ('EmojiStr_two', models.TextField(max_length=100)),
                ('EmojiArray_two', models.CharField(max_length=20)),
                ('PIN_two', models.CharField(max_length=4)),
            ],
        ),
    ]
