# Generated by Django 3.1.4 on 2020-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emojiauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logininfo',
            name='EmojiArray_one',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='EmojiArray_two',
            field=models.CharField(max_length=50),
        ),
    ]
